import { Artwork } from './types/artworks';

export const data: Artwork[] = [
  {
    id: 1,
    name: 'Bogorodica',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: 10,
      height: 15,
      radius: null,
    },
    status: 'available',
    price: '80.000,00 din',
  },
  {
    id: 2,
    name: 'Bogorodica',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: null,
      height: null,
      radius: 20,
    },
    status: 'sold',
  },
  {
    id: 3,
    name: 'Rodjenje Hristovo',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: 40,
      height: 50,
      radius: null,
    },
    status: 'sold',
  },
  {
    id: 4,
    name: 'Detalj',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: null,
      height: null,
      radius: null,
    },
    status: 'sold',
  },
  {
    id: 5,
    name: 'Detalj',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: null,
      height: null,
      radius: null,
    },
  },
  {
    id: 6,
    name: 'Hristos i Andjeo cuvar, diptih',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: 10,
      height: 15,
      radius: null,
    },
    status: 'sold',
  },
  {
    id: 7,
    name: 'Hristos isceljuje slepog',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: null,
      height: null,
      radius: 20,
    },
    status: 'available',
    price: '58.000,00 din',
  },
  {
    id: 8,
    name: 'Hristov ulazak u Jerusalim',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: 50,
      height: 60,
      radius: null,
    },
    status: 'sold',
  },
  {
    id: 9,
    name: 'Bozic, diptih',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: 15,
      height: 20,
      radius: null,
    },
    status: 'available',
    price: '65.000,00 din',
  },
  {
    id: 10,
    name: 'Blagovesti',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: null,
      height: null,
      radius: null,
    },
    status: 'sold',
  },
  {
    id: 11,
    name: 'Detalj',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: null,
      height: null,
      radius: null,
    },
  },
  {
    id: 12,
    name: 'Miscellaneous',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: null,
      height: null,
      radius: null,
    },
    status: 'sold',
  },
  {
    id: 13,
    name: 'Obrezanje i Hristova propoved u hramu',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: 50,
      height: 60,
      radius: null,
    },
    status: 'sold',
  },
  {
    id: 14,
    name: 'Propoved u hramu, detalj',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: null,
      height: null,
      radius: null,
    },
    status: 'sold',
  },
  {
    id: 15,
    name: 'Blagovesti',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: 10,
      height: 40,
      radius: null,
    },
    status: 'sold',
  },
  {
    id: 16,
    name: 'Sv Anastasija',
    category: 'icons',
    technique: 'Kombinovana tehnika na platnu',
    size: {
      width: null,
      height: null,
      radius: null,
    },
    status: 'sold',
  },
  // {
  //   id: ,
  //   name: "",
  //   category: "icons",
  //   technique: "Kombinovana tehnika na platnu",
  //   size: {
  //     width: null,
  //     height: null,
  //     radius: null
  //   },
  //   status: "sold"
  // },
];
