import {
  ABOUT_ELEMENT_ID,
  CONTACT_ELEMENT_ID,
  FILTER_ALL,
  FILTER_ICONS,
  FILTER_ILLUSTRATIONS,
  FILTER_NECKLACES,
  HOME_ELEMENT_ID,
  LANGUAGE_EN,
  LANGUAGE_RS,
  PORTFOLIO_ELEMENT_ID,
  RESUME_ELEMENT_ID,
} from './constants';

export const content = {
  navItems: [
    HOME_ELEMENT_ID,
    PORTFOLIO_ELEMENT_ID,
    ABOUT_ELEMENT_ID,
    RESUME_ELEMENT_ID,
    CONTACT_ELEMENT_ID,
  ],
  portfolio: {
    filters: [FILTER_ALL, FILTER_ILLUSTRATIONS, FILTER_ICONS, FILTER_NECKLACES],
  },
  languages: [LANGUAGE_RS, LANGUAGE_EN],
};
